# ─── Build stage ────────────────────────────────────────────────────────────
FROM golang:1.26-alpine AS builder

WORKDIR /src

# Dependencies layer — cached unless go.mod/go.sum change.
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# CGO_ENABLED=0: pure-Go binary (modernc.org/sqlite needs no C runtime).
RUN CGO_ENABLED=0 GOOS=linux go build \
    -ldflags="-s -w" \
    -trimpath \
    -o /bin/winupdate \
    ./cmd/winupdate

# ─── Runtime stage ───────────────────────────────────────────────────────────
FROM alpine:3.21

# ca-certificates: system root CA bundle (Go crypto/x509 reads from it).
# openssl:         cert generation in the entrypoint + DER → PEM conversion.
# curl:            health checks + downloading the Microsoft Update CA chain.
# tzdata:          time zone data (some WU timestamp parsing relies on local TZ).
RUN apk add --no-cache ca-certificates openssl curl tzdata

# ── Microsoft Update intermediate CAs ────────────────────────────────────────
# fe3.delivery.mp.microsoft.com  → Microsoft Update Secure Server CA 2.1 (RSA)
# fe3cr.delivery.mp.microsoft.com → Microsoft ECC Update Secure Server CA 2.1 (ECC)
#
# Neither is included in the Alpine/Mozilla root bundle; without them the Go
# HTTP client fails to verify the WU TLS chain.
RUN curl -sf \
    "http://www.microsoft.com/pkiops/certs/Microsoft%20Update%20Secure%20Server%20CA%202.1.crt" \
    -o /tmp/ms-rsa-ca.der \
  && openssl x509 -inform DER -in /tmp/ms-rsa-ca.der \
    >> /etc/ssl/certs/ca-certificates.crt \
  && curl -sf \
    "http://www.microsoft.com/pkiops/certs/Microsoft%20ECC%20Update%20Secure%20Server%20CA%202.1.crt" \
    -o /tmp/ms-ecc-ca.der \
  && openssl x509 -inform DER -in /tmp/ms-ecc-ca.der \
    >> /etc/ssl/certs/ca-certificates.crt \
  && rm -f /tmp/ms-rsa-ca.der /tmp/ms-ecc-ca.der

COPY --from=builder /bin/winupdate /usr/local/bin/winupdate
COPY scripts/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# /data  — SQLite database
# /certs — TLS certificates (generated by entrypoint if missing)
VOLUME ["/data", "/certs"]

EXPOSE 8443

ENTRYPOINT ["docker-entrypoint.sh"]
